# todo: use this config file somehow

socials:
  github:
    color: "#f171515"
    short: gh
    url: https://github.com/kwyntes
    username: "@kwyntes"
  youtube:
    color: "#f00"
    short: yt
    url: ...
    username: SAUNDIX
  soundcloud:
    color: "#f70"
    short: sc
    url: https://soundcloud.com/asynchronousongs
    username: SAUNDIX
